-- Platform Foundation: single-tenant-ready. Adds Company (tenant root) + Branch,
-- backfills every business table with a companyId scoped to the default company.

CREATE TABLE "Company" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Company_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Company_slug_key" ON "Company"("slug");
CREATE TABLE "Branch" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "name" TEXT NOT NULL, "isPrimary" BOOLEAN NOT NULL DEFAULT false, "address" TEXT, "createdById" TEXT, "updatedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Branch_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Branch_companyId_idx" ON "Branch"("companyId");
ALTER TABLE "Branch" ADD CONSTRAINT "Branch_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "Company"("id","name","slug","createdAt","updatedAt") VALUES ('a0000000-0000-4000-8000-000000000001','AZAD EV POINT','azad-ev-point',now(),now());
INSERT INTO "Branch"("id","companyId","name","isPrimary","createdAt","updatedAt") VALUES (gen_random_uuid(),'a0000000-0000-4000-8000-000000000001','Main Branch',true,now(),now());

ALTER TABLE "Accessory" ADD COLUMN "companyId" TEXT;
UPDATE "Accessory" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Accessory" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "ActivityLog" ADD COLUMN "companyId" TEXT;
UPDATE "ActivityLog" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "ActivityLog" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Booking" ADD COLUMN "companyId" TEXT;
UPDATE "Booking" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Booking" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "BookingDocument" ADD COLUMN "companyId" TEXT;
UPDATE "BookingDocument" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "BookingDocument" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Customer" ADD COLUMN "companyId" TEXT;
UPDATE "Customer" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Customer" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "CustomerDocument" ADD COLUMN "companyId" TEXT;
UPDATE "CustomerDocument" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "CustomerDocument" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "CustomerFollowUp" ADD COLUMN "companyId" TEXT;
UPDATE "CustomerFollowUp" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "CustomerFollowUp" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "CustomerNote" ADD COLUMN "companyId" TEXT;
UPDATE "CustomerNote" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "CustomerNote" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "CustomerTimelineEntry" ADD COLUMN "companyId" TEXT;
UPDATE "CustomerTimelineEntry" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "CustomerTimelineEntry" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Delivery" ADD COLUMN "companyId" TEXT;
UPDATE "Delivery" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Delivery" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Expense" ADD COLUMN "companyId" TEXT;
UPDATE "Expense" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Expense" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "FinanceDetail" ADD COLUMN "companyId" TEXT;
UPDATE "FinanceDetail" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "FinanceDetail" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InsuranceDetail" ADD COLUMN "companyId" TEXT;
UPDATE "InsuranceDetail" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InsuranceDetail" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InventoryEvent" ADD COLUMN "companyId" TEXT;
UPDATE "InventoryEvent" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InventoryEvent" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InventoryUnit" ADD COLUMN "companyId" TEXT;
UPDATE "InventoryUnit" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InventoryUnit" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InventoryUnitDocument" ADD COLUMN "companyId" TEXT;
UPDATE "InventoryUnitDocument" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InventoryUnitDocument" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InventoryUnitPhoto" ADD COLUMN "companyId" TEXT;
UPDATE "InventoryUnitPhoto" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InventoryUnitPhoto" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Notification" ADD COLUMN "companyId" TEXT;
UPDATE "Notification" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Notification" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Payment" ADD COLUMN "companyId" TEXT;
UPDATE "Payment" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Payment" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Quotation" ADD COLUMN "companyId" TEXT;
UPDATE "Quotation" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Quotation" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "Sale" ADD COLUMN "companyId" TEXT;
UPDATE "Sale" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "Sale" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "ScooterModel" ADD COLUMN "companyId" TEXT;
UPDATE "ScooterModel" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "ScooterModel" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "ScooterVariant" ADD COLUMN "companyId" TEXT;
UPDATE "ScooterVariant" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "ScooterVariant" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "ServiceJob" ADD COLUMN "companyId" TEXT;
UPDATE "ServiceJob" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "ServiceJob" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "TestRide" ADD COLUMN "companyId" TEXT;
UPDATE "TestRide" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "TestRide" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "User" ADD COLUMN "companyId" TEXT;
UPDATE "User" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "User" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "CompanySetting" ADD COLUMN "companyId" TEXT;
UPDATE "CompanySetting" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "CompanySetting" ALTER COLUMN "companyId" SET NOT NULL;
ALTER TABLE "InvoiceSetting" ADD COLUMN "companyId" TEXT;
UPDATE "InvoiceSetting" SET "companyId" = 'a0000000-0000-4000-8000-000000000001' WHERE "companyId" IS NULL;
ALTER TABLE "InvoiceSetting" ALTER COLUMN "companyId" SET NOT NULL;

CREATE INDEX "Accessory_companyId_idx" ON "Accessory"("companyId");
CREATE INDEX "ActivityLog_companyId_idx" ON "ActivityLog"("companyId");
CREATE INDEX "Booking_companyId_idx" ON "Booking"("companyId");
CREATE INDEX "BookingDocument_companyId_idx" ON "BookingDocument"("companyId");
CREATE INDEX "Customer_companyId_idx" ON "Customer"("companyId");
CREATE INDEX "CustomerDocument_companyId_idx" ON "CustomerDocument"("companyId");
CREATE INDEX "CustomerFollowUp_companyId_idx" ON "CustomerFollowUp"("companyId");
CREATE INDEX "CustomerNote_companyId_idx" ON "CustomerNote"("companyId");
CREATE INDEX "CustomerTimelineEntry_companyId_idx" ON "CustomerTimelineEntry"("companyId");
CREATE INDEX "Delivery_companyId_idx" ON "Delivery"("companyId");
CREATE INDEX "Expense_companyId_idx" ON "Expense"("companyId");
CREATE INDEX "FinanceDetail_companyId_idx" ON "FinanceDetail"("companyId");
CREATE INDEX "InsuranceDetail_companyId_idx" ON "InsuranceDetail"("companyId");
CREATE INDEX "InventoryEvent_companyId_idx" ON "InventoryEvent"("companyId");
CREATE INDEX "InventoryUnit_companyId_idx" ON "InventoryUnit"("companyId");
CREATE INDEX "InventoryUnitDocument_companyId_idx" ON "InventoryUnitDocument"("companyId");
CREATE INDEX "InventoryUnitPhoto_companyId_idx" ON "InventoryUnitPhoto"("companyId");
CREATE INDEX "Notification_companyId_idx" ON "Notification"("companyId");
CREATE INDEX "Payment_companyId_idx" ON "Payment"("companyId");
CREATE INDEX "Quotation_companyId_idx" ON "Quotation"("companyId");
CREATE INDEX "Sale_companyId_idx" ON "Sale"("companyId");
CREATE INDEX "ScooterModel_companyId_idx" ON "ScooterModel"("companyId");
CREATE INDEX "ScooterVariant_companyId_idx" ON "ScooterVariant"("companyId");
CREATE INDEX "ServiceJob_companyId_idx" ON "ServiceJob"("companyId");
CREATE INDEX "TestRide_companyId_idx" ON "TestRide"("companyId");
CREATE INDEX "User_companyId_idx" ON "User"("companyId");
CREATE UNIQUE INDEX "CompanySetting_companyId_key" ON "CompanySetting"("companyId");
CREATE UNIQUE INDEX "InvoiceSetting_companyId_key" ON "InvoiceSetting"("companyId");
